from datetime import datetime

class Log_data:
    version = 0
    dt = datetime.strptime('1900/1/1 0:0:0', '%Y/%m/%d %H:%M:%S')
    code = ""
    category = ""
    name = ""
    device_id = ""
    message_type = ""

    def get_Data(self):

        return {
            "version": self.version,
            "datetime": self.dt,
            "deviceID": self.device_id,
            "code": self.code,
            "category": self.category,
            "name": self.name,
            "messageType": self.message_type
        }

index = [
    {"code": "1000", "category": "P-Ven", "name": "OK", "messageType":"info"},
    {"code": "1001", "category": "P-Ven", "name": "Over upper warning limit", "messageType":"alert"},
    {"code": "1002", "category": "P-Ven", "name": "Under lower warning limit", "messageType":"alert"},
    {"code": "1003", "category": "P-Ven", "name": "Over upper alarm limit", "messageType":"alert"},
    {"code": "1004", "category": "P-Ven", "name": "Under lower alarm limit", "messageType":"alert"},
    {"code": "1005", "category": "P-Ven", "name": "Over upper stop limit", "messageType":"alert"},
    {"code": "1006", "category": "P-Ven", "name": "Under lower stop limit", "messageType":"alert"},
    {"code": "1008", "category": "P-Ven", "name": "Disconnected", "messageType":"alert"},
    {"code": "1009", "category": "P-Ven", "name": "Out of range", "messageType":"alert"},
    {"code": "100A", "category": "P-Ven", "name": "Defect", "messageType":"alert"},
    {"code": "2000", "category": "P-Int", "name": "OK", "messageType":"info"},
    {"code": "2001", "category": "P-Int", "name": "Over upper warning limit", "messageType":"alert"},
    {"code": "2002", "category": "P-Int", "name": "Under lower warning limit", "messageType":"alert"},
    {"code": "2003", "category": "P-Int", "name": "Over upper alarm limit", "messageType":"alert"},
    {"code": "2004", "category": "P-Int", "name": "Under lower alarm limit", "messageType":"alert"},
    {"code": "2005", "category": "P-Int", "name": "Over upper stop limit", "messageType":"alert"},
    {"code": "2006", "category": "P-Int", "name": "Under lower stop limit", "messageType":"alert"},
    {"code": "2008", "category": "P-Int", "name": "Disconnected", "messageType":"alert"},
    {"code": "2009", "category": "P-Int", "name": "Out of range", "messageType":"alert"},
    {"code": "200A", "category": "P-Int", "name": "Defect", "messageType":"alert"},
    {"code": "3000", "category": "P-Art", "name": "OK", "messageType":"info"},
    {"code": "3001", "category": "P-Art", "name": "Over upper warning limit", "messageType":"alert"},
    {"code": "3002", "category": "P-Art", "name": "Under lower warning limit", "messageType":"alert"},
    {"code": "3003", "category": "P-Art", "name": "Over upper alarm limit", "messageType":"alert"},
    {"code": "3004", "category": "P-Art", "name": "Under lower alarm limit", "messageType":"alert"},
    {"code": "3005", "category": "P-Art", "name": "Over upper stop limit", "messageType":"alert"},
    {"code": "3006", "category": "P-Art", "name": "Under lower stop limit", "messageType":"alert"},
    {"code": "3008", "category": "P-Art", "name": "Disconnected", "messageType":"alert"},
    {"code": "3009", "category": "P-Art", "name": "Out of range", "messageType":"alert"},
    {"code": "300A", "category": "P-Art", "name": "Defect", "messageType":"alert"},
    {"code": "4000", "category": "P-Aux", "name": "OK", "messageType":"info"},
    {"code": "4001", "category": "P-Aux", "name": "Over upper warning limit", "messageType":"alert"},
    {"code": "4002", "category": "P-Aux", "name": "Under lower warning limit", "messageType":"alert"},
    {"code": "4003", "category": "P-Aux", "name": "Over upper alarm limit", "messageType":"alert"},
    {"code": "4004", "category": "P-Aux", "name": "Under lower alarm limit", "messageType":"alert"},
    {"code": "4005", "category": "P-Aux", "name": "Over upper stop limit", "messageType":"alert"},
    {"code": "4006", "category": "P-Aux", "name": "Under lower stop limit", "messageType":"alert"},
    {"code": "4008", "category": "P-Aux", "name": "Disconnected", "messageType":"alert"},
    {"code": "4009", "category": "P-Aux", "name": "Out of range", "messageType":"alert"},
    {"code": "400A", "category": "P-Aux", "name": "Defect", "messageType":"alert"},
    {"code": "5000", "category": "⊿P", "name": "OK", "messageType":"info"},
    {"code": "5001", "category": "⊿P", "name": "Over warning limit", "messageType":"alert"},
    {"code": "5002", "category": "⊿P", "name": "Under warning limit", "messageType":"alert"},
    {"code": "5004", "category": "P-Aux", "name": "Out of range", "messageType":"alert"},
    {"code": "6000", "category": "Flow", "name": "OK", "messageType":"info"},
    {"code": "6001", "category": "Flow", "name": "Over warning limit", "messageType":"alert"},
    {"code": "6002", "category": "Flow", "name": "Under warning limit", "messageType":"alert"},
    {"code": "6005", "category": "Flow", "name": "Over stop limit", "messageType":"alert"},
    {"code": "6006", "category": "Flow", "name": "Under stop limit", "messageType":"alert"},
    {"code": "6008", "category": "Flow", "name": "Disconnected", "messageType":"alert"},
    {"code": "6009", "category": "Flow", "name": "Out of range", "messageType":"alert"},
    {"code": "600A", "category": "Flow", "name": "Defect", "messageType":"alert"},
    {"code": "600B", "category": "Flow", "name": "Negative", "messageType":"alert"},
    {"code": "600C", "category": "Flow", "name": "Temperature too high", "messageType":"alert"},
    {"code": "600D", "category": "Flow", "name": "Amplitude too small", "messageType":"alert"},
    {"code": "600E", "category": "Flow", "name": "Offset too high", "messageType":"alert"},
    {"code": "600F", "category": "Flow", "name": "Wrong calibration", "messageType":"alert"},
    {"code": "7000", "category": "T-Ven", "name": "OK", "messageType":"info"},
    {"code": "7001", "category": "T-Ven", "name": "Over warning limit", "messageType":"alert"},
    {"code": "7002", "category": "T-Ven", "name": "Under warning limit", "messageType":"alert"},
    {"code": "7004", "category": "T-Ven", "name": "Disconnected", "messageType":"alert"},
    {"code": "7005", "category": "T-Ven", "name": "Out of range", "messageType":"alert"},
    {"code": "7006", "category": "T-Ven", "name": "Defect", "messageType":"alert"},
    {"code": "8000", "category": "T-Art", "name": "OK", "messageType":"info"},
    {"code": "8001", "category": "T-Art", "name": "Over warning limit", "messageType":"alert"},
    {"code": "8002", "category": "T-Art", "name": "Under warning limit", "messageType":"alert"},
    {"code": "8004", "category": "T-Art", "name": "Disconnected", "messageType":"alert"},
    {"code": "8005", "category": "T-Art", "name": "Out of range", "messageType":"alert"},
    {"code": "8006", "category": "T-Art", "name": "Defect", "messageType":"alert"},
    {"code": "9000", "category": "SvO2", "name": "OK", "messageType":"info"},
    {"code": "9001", "category": "SvO2", "name": "Over warning limit", "messageType":"alert"},
    {"code": "9002", "category": "SvO2", "name": "Under warning limit", "messageType":"alert"},
    {"code": "9003", "category": "SvO2", "name": "Out of range", "messageType":"alert"},
    {"code": "9004", "category": "SvO2", "name": "Defect", "messageType":"alert"},
    {"code": "9006", "category": "SvO2", "name": "Disconnected", "messageType":"alert"},
    {"code": "A000", "category": "Bubble", "name": "OK", "messageType":"info"},
    {"code": "A001", "category": "Bubble", "name": "Bubble detected without intervention", "messageType":"alert"},
    {"code": "A002", "category": "Bubble", "name": "Bubble detected with intervention", "messageType":"alert"},
    {"code": "A003", "category": "Bubble", "name": "Disconnected", "messageType":"alert"},
    {"code": "A004", "category": "Bubble", "name": "Out of range", "messageType":"alert"},
    {"code": "A005", "category": "Bubble", "name": "Defect", "messageType":"alert"},
    {"code": "A008", "category": "Bubble", "name": "Reset", "messageType":"alert"},
    {"code": "C000", "category": "Level", "name": "OK", "messageType":"info"},
    {"code": "C001", "category": "Level", "name": "Level detected without intervention", "messageType":"alert"},
    {"code": "C002", "category": "Level", "name": "Level detected with intervention", "messageType":"alert"},
    {"code": "C003", "category": "Level", "name": "Disconnected", "messageType":"alert"},
    {"code": "C004", "category": "Level", "name": "Out of range", "messageType":"alert"},
    {"code": "C005", "category": "Level", "name": "Defect", "messageType":"alert"},
    {"code": "D000", "category": "Speed(RPM)", "name": "OK", "messageType":"info"},
    {"code": "D001", "category": "Speed(RPM)", "name": "Over warning limit", "messageType":"alert"},
    {"code": "D002", "category": "Speed(RPM)", "name": "Under warning limit", "messageType":"alert"},
    {"code": "D003", "category": "Speed(RPM)", "name": "Over stop limit", "messageType":"alert"},
    {"code": "D004", "category": "Speed(RPM)", "name": "Under stop limit", "messageType":"alert"},
    {"code": "D007", "category": "Speed(RPM)", "name": "Out of range", "messageType":"alert"},
    {"code": "D00C", "category": "Pump status", "name": "Running", "messageType":"info"},
    {"code": "D00D", "category": "Pump status", "name": "Stopped", "messageType":"info"},
    {"code": "E000", "category": "Hct", "name": "OK", "messageType":"info"},
    {"code": "E001", "category": "Hct", "name": "Over warning limit", "messageType":"alert"},
    {"code": "E002", "category": "Hct", "name": "Under warning limit", "messageType":"alert"},
    {"code": "E003", "category": "Hct", "name": "Out of range", "messageType":"alert"},
    {"code": "E004", "category": "Hct", "name": "Defect", "messageType":"alert"},
    {"code": "E005", "category": "Hct", "name": "Disconnected", "messageType":"alert"},
    {"code": "F000", "category": "Hb", "name": "OK", "messageType":"info"},
    {"code": "F001", "category": "Hb", "name": "Over warning limit", "messageType":"alert"},
    {"code": "F002", "category": "Hb", "name": "Under warning limit", "messageType":"alert"},
    {"code": "F003", "category": "Hb", "name": "Out of range", "messageType":"alert"},
    {"code": "F004", "category": "Hb", "name": "Defect", "messageType":"alert"},
    {"code": "F005", "category": "Hb", "name": "Disconnected", "messageType":"alert"},
    {"code": "F006", "category": "Hb", "name": "Limit changed", "messageType":"alert"},
]